
DROP TABLE IF EXISTS `guest_data`;
CREATE TABLE `guest_data` (
    id BIGINT AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    age INT DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    balance DECIMAL(10,2) DEFAULT 0.00,
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB;

